blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from .views import *


urlpatterns = [
    path('blog/', blog, name="blog"),
    path('blog_sorting/', blog_sorting, name="blog_sorting"),
    re_path(r'^blog/(?P<category_link>.+)/(?P<article_link>[\w\d\W]+)/$', article_or_category, name='article'),
    re_path(r'^blog/(?P<category_link>.+)/$', category, name='category_blog'),
]

grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
from django.conf.urls import url
# from django.views.generic import TemplateView

# GRAPPELLI IMPORTS
from .views.related import RelatedLookup, M2MLookup, AutocompleteLookup
from .views.switch import switch_user


urlpatterns = [

    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', RelatedLookup.as_view(), name="grp_related_lookup"),
    url(r'^lookup/m2m/$', M2MLookup.as_view(), name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', AutocompleteLookup.as_view(), name="grp_autocomplete_lookup"),

    # SWITCH USER
    url(r'^switch/user/(?P<object_id>\d+)/$', switch_user, name="grp_switch_user"),

    # GRAPPELLI DOM DOCUMENTATION
    # url(r'^grp-doc/change-form/', TemplateView.as_view(template_name='grp_doc/change_form.html'), name="grp_doc_change_form"),
    # url(r'^grp-doc/change-list/', TemplateView.as_view(template_name='grp_doc/change_list.html'), name="grp_doc_change_list"),
    # url(r'^grp-doc/admin-index/', TemplateView.as_view(template_name='grp_doc/admin_index.html'), name="grp_doc_admin_index"),
    #
    # url(r'^grp-doc/tables/', TemplateView.as_view(template_name='grp_doc/tables.html'), name="grp_doc_tables"),
    #
    # url(r'^grp-doc/pagination/', TemplateView.as_view(template_name='grp_doc/pagination.html'), name="grp_doc_pagination"),
    # url(r'^grp-doc/search-form/', TemplateView.as_view(template_name='grp_doc/search_form.html'), name="grp_doc_search_form"),
    # url(r'^grp-doc/filter/', TemplateView.as_view(template_name='grp_doc/filter.html'), name="grp_doc_filter"),
    # url(r'^grp-doc/date-hierarchy/', TemplateView.as_view(template_name='grp_doc/date_hierarchy.html'), name="grp_doc_date_hierarchy"),
    #
    # url(r'^grp-doc/fieldsets/', TemplateView.as_view(template_name='grp_doc/fieldsets.html'), name="grp_doc_fieldsets"),
    # url(r'^grp-doc/errors/', TemplateView.as_view(template_name='grp_doc/errors.html'), name="grp_doc_errors"),
    # url(r'^grp-doc/form-fields/', TemplateView.as_view(template_name='grp_doc/form_fields.html'), name="grp_doc_form_fields"),
    # url(r'^grp-doc/submit-rows/', TemplateView.as_view(template_name='grp_doc/submit_rows.html'), name="grp_doc_submit_rows"),
    #
    # url(r'^grp-doc/modules/', TemplateView.as_view(template_name='grp_doc/modules.html'), name="grp_doc_modules"),
    # url(r'^grp-doc/groups/', TemplateView.as_view(template_name='grp_doc/groups.html'), name="grp_doc_groups"),
    #
    # url(r'^grp-doc/navigation/', TemplateView.as_view(template_name='grp_doc/navigation.html'), name="grp_doc_navigation"),
    # url(r'^grp-doc/context-navigation/', TemplateView.as_view(template_name='grp_doc/context_navigation.html'), name="grp_doc_context_navigation"),
    #
    # url(r'^grp-doc/basic-page-structure/', TemplateView.as_view(template_name='grp_doc/basic_page_structure.html'), name="grp_doc_basic_page_structure"),
    #
    # url(r'^grp-doc/tools/', TemplateView.as_view(template_name='grp_doc/tools.html'), name="grp_doc_tools"),
    # url(r'^grp-doc/object-tools/', TemplateView.as_view(template_name='grp_doc/object_tools.html'), name="grp_doc_object_tools"),
    #
    # url(r'^grp-doc/mueller-grid-system-tests/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_tests.html'), name="grp_doc_mueller_grid_system_tests"),
    # url(r'^grp-doc/mueller-grid-system/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system.html'), name="grp_doc_mueller_grid_system"),
    # url(r'^grp-doc/mueller-grid-system-layouts/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_layouts.html'), name="grp_doc_mueller_grid_system_layouts"),
    #
    # url(r'^grp-doc', TemplateView.as_view(template_name='grp_doc/index.html'), name="grp_doc"),

]

mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from .api import *

urlpatterns = [
    path('', index, name="index"),
    path('contacts/', contacts, name="contacts"),
    path('reglament/', reglament, name="reglament"),
    path("register/", register_page, name="register_page"),
    path("logout_user/", logout_user, name="logout_user"),
    path("login/", login_page, name="login_page"),
    path("account/", account_page, name="account_page"),
    path("api/login_json/", login_json, name="login_json"),
    path("api/register_json/", register_json, name="register_json"),
]

orders/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

app_name = 'orders'
urlpatterns = [
    path('order_created/<int:price>/<int:product_id>/', order_created, name='order_created'),
]

pigeon/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.views.static import serve
from filebrowser.sites import site

from mainapp import context_processors

urlpatterns = [
                  path('admin/filebrowser/', site.urls),
                  path('grappelli/', include('grappelli.urls')),
                  path('admin/', admin.site.urls),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('lang/', context_processors.lang, name="lang"),
                  path('paypal/', include('paypal.standard.ipn.urls')),
                  path('orders/', include('orders.urls'), name='orders'),
                  path('payment/', include('payment.urls'), name='payment'),
                  re_path(r'^static/(?P<path>.*)$', serve,
                          {'document_root': settings.STATIC_ROOT}),
                  re_path(r'^media/(?P<path>.*)$', serve,
                          {'document_root': settings.MEDIA_ROOT}),
                  path('favicon.ico', RedirectView.as_view(url='/media/icons/faicon.ico'), name='favicon'),
                  path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path("", include("mainapp.urls")),
    path("", include("products.urls")),
    path("", include("blog.urls")),
    path("", include("slider.urls")),
    path("", include("send_email.urls")),
    path("", include("forum.urls")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False,
)

mainapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.cache import cache
from django.conf import settings
from datetime import datetime, timedelta
from django.utils import timezone
# Create your models here.
from ckeditor_uploader.fields import RichTextUploadingField
from filebrowser.base import FileObject
from filebrowser.fields import FileBrowseField


class CurrencySettings(models.Model):
    name = models.CharField(null=False, max_length=100)
    price = models.DecimalField(null=False, max_digits=9, decimal_places=5)

    def __str__(self):
        return self.name


class Profile(models.Model):
    phone = models.CharField(max_length=30, default="")
    user_fk = models.OneToOneField(User, on_delete=models.CASCADE, default=None, blank=True, null=True)
    online = models.BooleanField(default=False)
    image = models.ImageField(upload_to='account', default='no-image.png')
    description = RichTextUploadingField(null=True, blank=True, default="")
    last_seen = models.DateTimeField(auto_now_add=False, auto_now=False, default=timezone.now)

    def __str__(self):
        return self.user_fk.username

    def method_last_seen(self):
        return cache.get('seen_%s' % self.user_fk.username)

    def method_online(self):
        if self.method_last_seen():
            now = datetime.now()
            if now > self.method_last_seen() + timedelta(seconds=settings.USER_ONLINE_TIMEOUT):
                return False
            else:
                return True
        else:
            return False

mainapp/views.py
import json

from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

from mainapp.models import Profile
from slider.get_data import *


# Create your views here.


def index(request):
    return render(request, 'mainapp/index.html', {'main_slider_top': get_slider_by_name('Reklamy')})


def contacts(request):
    return render(request, "mainapp/contacts.html")


def reglament(request):
    return render(request, "mainapp/reglament.html")


def logout_user(request):
    user = request.user
    logout(request)
    return redirect('/')
    # return HttpResponse("success")


def register_page(request):
    if request.user.is_authenticated:
        return redirect('/')
    return render(request, "mainapp/register.html", locals())


def login_page(request):
    if request.user.is_authenticated:
        return redirect('/')
    return render(request, "mainapp/login.html", locals())


def account_page(request):
    if not request.user.is_authenticated:
        return redirect('/')
    return render(request, "mainapp/account.html", {'profile': Profile.objects.get(user_fk_id=request.user.pk)})

mainapp/templates/mainapp/account.html
{% extends "wraper.html" %}
{% load i18n %}
{% load mainapp_tags %}
{% load orders_tags %}
{% block body %}
    {% tag_get_currency_pln as PLN %}
    <div class="container">
        <nav class="pt-5">
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">{% trans "Home" %}</a>
                <a class="nav-item nav-link" id="nav-bets-tab" data-toggle="tab" href="#nav-bets" role="tab" aria-controls="nav-bets" aria-selected="false">{% trans "Moje zakłady" %}</a>
                <a class="nav-item nav-link" id="nav-bets-win-tab" data-toggle="tab" href="#nav-bets-win" role="tab" aria-controls="nav-bets-win"
                   aria-selected="false">{% trans "Moje zakłady wygrane" %}</a>
                <a class="nav-item nav-link" id="nav-orders-tab" data-toggle="tab" href="#nav-orders" role="tab" aria-controls="nav-orders" aria-selected="false">{% trans "Orders" %}</a>
            </div>
        </nav>
        <div class="tab-content pt-3" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                <div class="d-flex justify-content-start align-items-center flex-wrap">
                    <i class="fas fa-user fa-4x"></i>
                    <div class="d-inline-block ml-3">
                        <div>
                            <span class="font-weight-bold">{% trans "User Name" %}: </span><label class="label label-info">{{ user.username }}</label>
                        </div>
                        <div>
                            <span class="font-weight-bold">{% trans "Email" %}: </span> <label class="label label-info">{{ user.email }}</label>
                        </div>
                        <div>
                            <span class="font-weight-bold">{% trans "Phone" %}: </span> <label class="label label-info">{{ profile.phone }}</label>
                        </div>
                        <div>
                            <span class="font-weight-bold">{% trans "First Name" %}: </span> <label class="label label-info">{{ user.first_name }}</label>
                        </div>
                        <div>
                            <span class="font-weight-bold">{% trans "Last Name" %}: </span> <label class="label label-info">{{ user.last_name }}</label>
                        </div>
                    </div>
                    <div class="d-inline-block ml-3">
                        <img width="100" height="100" style="width: inherit; height: 300px; object-fit: contain;" src="{{ profile.image.url }}" alt="">
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="nav-bets" role="tabpanel" aria-labelledby="nav-bets-tab">
                {% tag_user_bets user.pk as bets %}

                <h1 class="w-100">{% trans "Last Bets" %}</h1>
                {% if bets %}
                    <div class="row">
                        {% for bet in bets %}
                            <div class="col-12 col-lg-6">
                                <a href="{{ bet.data.product.link }}">{{ bet.data.product.name }}</a>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="row no-gutters">
                                    <div class="col-5 col-lg-4">
                                        <div class="bet-price-account">
                                            <div class="d-inline">{{ bet.object.price }} <span class="bet-price-symbol-account">EUR</span></div>
                                            /
                                            <div class="d-inline">{{ bet.object.price|filter_convert_eur_to_pln }} <span class="bet-price-symbol-account">PLN</span></div>
                                        </div>
                                    </div>
                                    <div class="col-7 col-lg-8">
                                        <div class="bet-date float-right w-auto">{{ bet.object.added_date|date:"Y-m-d H:i:s" }}</div>
                                    </div>
                                </div>
                            </div>
                            <hr class="w-100">
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="h5">{% trans "No bets" %}</div>
                {% endif %}
            </div>
            <div class="tab-pane fade" id="nav-bets-win" role="tabpanel" aria-labelledby="nav-bets-win-tab">
                {% tag_user_bets_win user.pk as bets_win %}
                <div class="w-100 h1">{% trans "Winning lots" %}</div>
                {% if bets_win %}
                    <div class="row">
                        {% for bet in bets_win %}
                            <div class="col-12 col-lg-5">
                                <a href="{{ bet.data.product.link }}">{{ bet.data.product.name }}</a>
                            </div>
                            <div class="col-12 col-lg-7">
                                <div class="row no-gutters">
                                    <div class="col-3 col-lg-3">
                                        <div class="bet-price-account">
                                            <div class="d-inline">{{ bet.object.price }} <span class="bet-price-symbol-account">EUR</span></div>
                                            /
                                            <div class="d-inline">{{ bet.object.price|filter_convert_eur_to_pln }} <span class="bet-price-symbol-account">PLN</span></div>
                                        </div>
                                    </div>
                                    <div class="col-6 col-lg-7">
                                        <div class="bet-date float-right w-auto">{{ bet.object.added_date|date:"Y-m-d H:i:s" }}</div>
                                    </div>
                                    <div class="col-3 col-lg-2">
                                        {% if bet.data.payment %}
                                            <div class="btn btn-success w-100 ml-1 mr-1 p-0"><i class="fas fa-check"></i> {% trans "Paid" %}</div>
                                        {% else %}
                                            <a href="{% url 'orders:order_created' bet.object.price|filter_convert_eur_to_pln bet.data.product.pk %}" class="btn btn-secondary w-100 ml-1 mr-1 p-0"><i
                                                    class="fas fa-dollar-sign"></i>
                                                {% trans "To pay" %}</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <hr class="w-100">
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="h5">{% trans "No bets won" %}</div>
                {% endif %}
            </div>
            <div class="tab-pane fade" id="nav-orders" role="tabpanel" aria-labelledby="nav-orders-tab">
                {% tag_user_orders request.user.pk as orders %}
                <div class="w-100 h1">{% trans 'Orders' %}</div>
                {% if orders %}
                    {% for order in orders %}
                        <div class="row">
                            <div class="col-4">{{ order.object.product }}</div>
                            <div class="col-4">{{ order.object.price_PLN }} <span>PLN</span></div>
                            <div class="col-4">{{ order.object.added_date|date:"Y-m-d H:i:s" }}</div>
                        </div>
                        <hr class="w-100">
                    {% endfor %}
                {% else %}
                    <div class="h5">{% trans 'No orders' %}</div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/contacts.html
{% extends "wraper.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load staticfiles %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="wow fadeInUp contact-info" data-wow-delay="0.4s">
                         <div class="section-title">
                              <h2>KONTAKT</h2>
                              <p>
                                  Santander Bank Polska:<br> 43 1090 2226 0000 0001 3053 3448
{#                                Konto Walutowe<br>#}
{#                                BZWBK, numer konta<br>#}
{#                                67 1090 2226 0000 0001 4265 6464<br>#}
{#                                <br>#}
{#                                Konto bankowe PL<br>#}
{#                                BZWBK, numer konta<br>#}
{#                                98 1090 2226 0000 0001 4265 6391<br>#}
                              </p>
                         </div>

                         <p><i class="fas fa-map-marker"></i>  Poland </p>
                         <p><i class="fas fa-comment"></i> <a href="mailto:info@company.com">ipacom24@gmail.com</a></p>
                         <p><i class="fas fa-phone"></i> +48 602 706 686</p>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends "wraper.html" %}
{% load blog_tags %}
{% load products_tags %}
{% load mainapp_tags %}
{% load slider_tags %}
{% load send_email_tags %}
{% load i18n %}
{% block body %}
        {% tag_get_last_lots as last_lots %}
    <div id="last_lots" class="last-lots mt-2 mb-2 container">
        {% for l_l in last_lots %}
            <div class="last-lot">
                <div class="last-lot-block">
                    <div class="image-container">
                        <img class="image-last-lot" src="{{ l_l.image.url }}" alt="">
                    </div>
                    <div class="info-container">
                        <div class="name">{{ l_l.name }}</div>
                        <div class="add-date">{{ l_l.added_date|date:"Y/m/d H:i"  }}</div>
                    </div>
                    <div class="price-container">
                        <div class="last-price">{{ l_l.current_price }} EUR</div>
                    </div>
                    <div class="action-container">
                        <a href="{{ l_l.link }}"><i class="fa fa-shopping-basket"></i></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
        $("#last_lots").slick({
            slidesToScroll: 1,
            arrows: true,
            dots: false,
            infinite: true,
            centerMode: true,
            variableWidth: true,
        });
    </script>


    <!--Слайдер-->
    {% if main_slider_top.data %}
        <div class="bloc-slider  mb-5 container">
            <div id="main-slider" class="carousel slide" data-ride="carousel">
                <ul class="carousel-indicators">
                    {% for slide in main_slider_top.data %}
                        <li data-target="#main-slider" data-slide-to="{{ forloop.counter0 }}"
                            class="{% if forloop.first %}active{% endif %}"></li>
                    {% endfor %}

                </ul>
                <div class="carousel-inner">
                    {% for slide in main_slider_top.data %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <img src="/media/{{ slide.image }}" alt="Los Angeles"
                                 style="width: 100%;
                                        {#height: 600px;#}
                                        filter: brightness(0.8);
                                        {#max-height: 100vh;#}
                                        display: block;
                                        object-fit: cover;
                                        object-position: center;">
                            <div class="carousel-caption">
                                {#                        <h3>Los Angeles</h3>#}
                                {#                        <p>We had such a great time in LA!</p>#}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#main-slider" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#main-slider" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>
        </div>
    {% endif %}



    <!--Головні категорії-->
    <div class="container mb-5">
        <div class="title-categories-main-page text-uppercase text-center mb-3">{% trans "Sellers" %}</div>
        <div id="main-slider-category" class="main-slider-category" style="max-width:100%;">
            {% tag_get_all_categories as all_categories %}
            {% for category in all_categories %}
                <div class="col-12">
                    <img class="img-fluid w-100" style="height: 170px; object-fit: cover; width: 450px!important;" src="{{ category.data.image }}"
                         alt="{{ category.data.name }}">
                    <a href="{{ category.data.link }}" class="text h4 text-center d-block">{{ category.data.name }}</a>
                </div>
            {% endfor %}
        </div>
    </div>

    <script>
        $("#main-slider-category").slick({
            slidesToScroll: 1,
            arrows: true,
            dots: true,
            infinite: true,
            centerMode: true,
            variableWidth: true,
            responsive: [
                {
                    breakpoint: 768,
                    settings: {
                        slidesToScroll: 1,
                        arrows: true,
                        dots: true,
                        infinite: true,
                        centerMode: true,
                        variableWidth: true,
                    }
                },
                {
                    breakpoint: 480,
                    settings: {
                        slidesToScroll: 1,
                        arrows: true,
                        dots: true,
                        infinite: true,
                        centerMode: true,
                        variableWidth: true,
                    }
                }
            ]
        });
    </script>


    <div class="container mb-5">
        <div class="row">
            <!--Останні новини блогу-->
            <div class="col-12 col-md-8">
                <div class="title-last-articles text-uppercase text-center mb-3">{% trans "Last Articles" %}</div>
                <div class="row">
                    {% tag_last_articles 3 as last_articles %}
                    {% for article in last_articles %}
                        <div class="col-12 col-sm-12 col-md-12 col-lg-4 mb-4 mb-lg-0 article-widget-cart">
                            <img style="height: 200px; width: 100%; object-fit: cover;" src="{{ article.data.image }}" alt="">
                            <a style="color: #000" href="{{ article.data.link }}">{{ article.data.name }}</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!--Останні ставки-->
            <div class="col-12 col-md-4 container-last-bets">
                {% tag_get_last_bets 10 as last_bets %}
                <div class="title-last-bets text-uppercase text-center mb-3">{% trans "Last Bets" %}</div>
                <div class="block-last-bets">
                    {% for last_bet in last_bets.object %}
                        <div class="last-bet">
                            <a class="product-name" href="{{ last_bet.product_fk.get_absolute_url }}">{{ last_bet.product_fk.get_fields.name }}</a>
                            <div class="price">{{ last_bet.price }} EUR / {{ last_bet.price|filter_convert_eur_to_pln }} PLN</div>
                            <div class="author-name">{{ last_bet.user_fk.username }}</div>
                            <div class="added-date">{{ last_bet.added_date|date:"Y-m-d H:i:s" }}</div>
                        </div>
                        <hr class="mt-1 mb-1">
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-lg-4">
                {% tag_get_slider_youtube 'ipa24video-darmove' %}
            </div>
            <div class="col-12 col-lg-8">
                {% tag_get_feedback %}
            </div>
        </div>
    </div>
    <div class="container">

    </div>
{% endblock %}

mainapp/templates/mainapp/login.html
{% extends "wraper.html" %}
{% load staticfiles %}
{% load i18n %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="offset-2 col-8 offset-md-4 col-md-4">
                <form class="mt-5" id="auth_form-login_page" method="post" action="{% url 'login_json' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="auth_name-login_page">{% trans "Login" %}</label>
                        <input type="text" id="auth_name-login_page" name="auth_name-login_page" class="form-control" aria-describedby="emailHelp" placeholder="Enter login" value="">
                    </div>
                    <div class="form-group">
                        <label for="auth_password-login_page">{% trans "Password" %}</label>
                        <input type="password" id="auth_password-login_page" name="auth_password-login_page" class="form-control" placeholder="Password" value="">
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/options.html
<option value="-1" selected>-------</option>
{% for option in options %}
    <option value="{{ option.attribute_value_fk.id }}">{{ option.value }}</option>
{% endfor %}